### ISSUE TITLE
Is there any Apple Watch solution with WearAuthn

### ISSUE THREAD

**Issue by thedreamwork** [FabianHenneke/WearAuthn#7]
Hi there!

Great app! 

Apple released apple watch many years and its product has a lot of user. Is it possible let apple watch as Security Key?

**Comment by FabianHenneke** [comment]
Hey, thanks for your interest.

Unfortunately, I neither own an Apple Watch nor have any experience developing for it. I even don't know whether watchOS allows third-party apps sufficient API access to implement a security key. It is thus very unlikely that I will be able to offer a watchOS version of WearAuthn.

That said, if there is anybody with the required skill set, I would be very glad to support them on the WebAuthn/CTAP2 side of things.
